version: '3'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5001:5000" 
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - registry-network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=SUPMIT Docker Registry
      - REGISTRY_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-network

networks:
  registry-network:
    driver: bridge

volumes:
  registry-data: